src/Entity/Consulta.php
<?php

namespace App\Entity;

use App\Repository\ConsultaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConsultaRepository::class)
 */
class Consulta
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $motivo_consulta;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="consultas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Paciente::class, inversedBy="consultas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $paciente;

    /**
     * @ORM\OneToOne(targetEntity=SignosVitales::class, mappedBy="consulta", cascade={"persist", "remove"})
     */
    private $signosVitales;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotivoConsulta(): ?string
    {
        return $this->motivo_consulta;
    }

    public function setMotivoConsulta(string $motivo_consulta): self
    {
        $this->motivo_consulta = $motivo_consulta;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPaciente(): ?Paciente
    {
        return $this->paciente;
    }

    public function setPaciente(?Paciente $paciente): self
    {
        $this->paciente = $paciente;

        return $this;
    }

    public function getSignosVitales(): ?SignosVitales
    {
        return $this->signosVitales;
    }

    public function setSignosVitales(SignosVitales $signosVitales): self
    {
        // set the owning side of the relation if necessary
        if ($signosVitales->getConsulta() !== $this) {
            $signosVitales->setConsulta($this);
        }

        $this->signosVitales = $signosVitales;

        return $this;
    }
}

src/Entity/Paciente.php
<?php

namespace App\Entity;

use App\Repository\PacienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PacienteRepository::class)
 */
class Paciente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellido;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Sexo;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cedula;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $image_profile;

    private $rawPhoto;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha_ingreso;

    /**
     * @ORM\OneToMany(targetEntity=Consulta::class, mappedBy="paciente", orphanRemoval=true)
     */
    private $consultas;

    public function __construct()
    {
        $this->consultas = new ArrayCollection();
    }

public function displayPhoto()
{
    if(null === $this->rawPhoto && $this->getImageProfile() != null) {
        $this->rawPhoto = "data:image/png;base64," . base64_encode(stream_get_contents($this->getImageProfile()));
    }

    return $this->rawPhoto;
}


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->Sexo;
    }

    public function setSexo(string $Sexo): self
    {
        $this->Sexo = $Sexo;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getCedula(): ?string
    {
        return $this->cedula;
    }

    public function setCedula(string $cedula): self
    {
        $this->cedula = $cedula;

        return $this;
    }

    public function getImageProfile()
    {
        return $this->image_profile;
    }

    public function setImageProfile($image_profile): self
    {
        $this->image_profile = $image_profile;

        return $this;
    }

    public function getFechaIngreso(): ?\DateTimeInterface
    {
        return $this->fecha_ingreso;
    }

    public function setFechaIngreso(?\DateTimeInterface $fecha_ingreso): self
    {
        $this->fecha_ingreso = $fecha_ingreso;

        return $this;
    }

    /**
     * @return Collection<int, Consulta>
     */
    public function getConsultas(): Collection
    {
        return $this->consultas;
    }

    public function addConsulta(Consulta $consulta): self
    {
        if (!$this->consultas->contains($consulta)) {
            $this->consultas[] = $consulta;
            $consulta->setPaciente($this);
        }

        return $this;
    }

    public function removeConsulta(Consulta $consulta): self
    {
        if ($this->consultas->removeElement($consulta)) {
            // set the owning side to null (unless already changed)
            if ($consulta->getPaciente() === $this) {
                $consulta->setPaciente(null);
            }
        }

        return $this;
    }
}

src/Form/ConsultaType.php
<?php

namespace App\Form;

use App\Entity\Consulta;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('motivo_consulta')
            ->add('fecha')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Consulta::class,
        ]);
    }
}

src/Controller/ConsultaController.php
<?php

namespace App\Controller;

use App\Entity\Consulta;
use App\Form\ConsultaType;
use App\Repository\ConsultaRepository;
use App\Repository\PacienteRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/consulta")
 */
class ConsultaController extends AbstractController
{
    /**
     * @Route("/", name="app_consulta_index", methods={"GET"}, options={"expose"=true})
     */
    public function index(ConsultaRepository $consultaRepository): Response
    {
        return $this->render('consulta/index.html.twig', [
            'consultas' => $consultaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="app_consulta_new", methods={"GET", "POST"},options={"expose"=true})
     */
    public function new(Request $request, ConsultaRepository $consultaRepository, $id, PacienteRepository $pacienteRepository, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $paciente= $pacienteRepository->find($id);
        $usuario = $userRepository->find($user);
        $consultum = new Consulta();
        $form = $this->createForm(ConsultaType::class, $consultum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $consultum->setUser($user);
            $consultum->setPaciente($paciente);
            $consultaRepository->add($consultum, true);

            return $this->redirect($request->getUri());
        }

        return $this->renderForm('consulta/new.html.twig', [
            'paciente'=> $paciente,
            'consultas' => $consultaRepository->findBy(
                ['paciente'=> $paciente,
                'user'=>$usuario
                ]
                
            ),
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_consulta_show", methods={"GET"})
     */
    public function show(Consulta $consultum): Response
    {
        return $this->render('consulta/show.html.twig', [
            'consultum' => $consultum,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_consulta_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Consulta $consultum, ConsultaRepository $consultaRepository): Response
    {
        $form = $this->createForm(ConsultaType::class, $consultum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $consultaRepository->add($consultum, true);

            return $this->redirectToRoute('app_consulta_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('consulta/edit.html.twig', [
            'consultum' => $consultum,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_consulta_delete", methods={"POST"})
     */
    public function delete(Request $request, Consulta $consultum, ConsultaRepository $consultaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$consultum->getId(), $request->request->get('_token'))) {
            $consultaRepository->remove($consultum, true);
        }

        return $this->redirectToRoute('app_consulta_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/consulta/_delete_form.html.twig
<form method="post" action="{{ path('app_consulta_delete', {'id': consultum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ consultum.id) }}">
    <button class="btn">Delete</button>
</form>

templates/consulta/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/consulta/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Consulta{% endblock %}

{% block body %}
    <h1>Edit Consulta</h1>

    {{ include('consulta/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_consulta_index') }}">back to list</a>

    {{ include('consulta/_delete_form.html.twig') }}
{% endblock %}

templates/consulta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consulta index{% endblock %}

{% block body %}
    <h1>Consulta index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Motivo_consulta</th>
                <th>Fecha</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for consultum in consultas %}
            <tr>
                <td>{{ consultum.id }}</td>
                <td>{{ consultum.motivoConsulta }}</td>
                <td>{{ consultum.fecha ? consultum.fecha|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_consulta_show', {'id': consultum.id}) }}">show</a>
                    <a href="{{ path('app_consulta_edit', {'id': consultum.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/consulta/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Consulta{% endblock %}

{% block body %}
 
  
  <div class="card mb-3" style="max-width: 750px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ paciente.displayPhoto}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ paciente.Nombre }} {{ paciente.Apellido }}</h5>
        <p class="card-text">Cedula: {{ paciente.cedula }} </p>
        <p class="card-text">Edad: {{ date('now').diff((date(paciente.fechaNacimiento))).format('%y años') }}</p>
        <p class="card-text">Fecha de Nacimiento: {{ paciente.fechaNacimiento ? paciente.fechaNacimiento|date('Y-m-d') : '' }}</p>
        <p class="card-text">Fecha de Ingreso: {{ paciente.fechaIngreso ? paciente.fechaIngreso|date('Y-m-d') : '' }}</p>
        <p class="card-text">Sexo: {{paciente.sexo}}</p>
      </div>
    </div>
  </div>
</div>

    {{ include('consulta/_form.html.twig') }}

    <table class="table">
        <thead>
            <tr>
                <th>Motivo_consulta</th>
                <th>Fecha</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for consultum in consultas %}
            <tr>
                <td>{{ consultum.motivoConsulta }}</td>
                <td>{{ consultum.fecha ? consultum.fecha|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_consulta_show', {'id': consultum.id}) }}">show</a>
                    <a href="{{ path('app_consulta_edit', {'id': consultum.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_paciente_index') }}">back to list</a>
{% endblock %}

templates/consulta/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consulta{% endblock %}

{% block body %}
    <h1>Consulta</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ consultum.id }}</td>
            </tr>
            <tr>
                <th>Motivo_consulta</th>
                <td>{{ consultum.motivoConsulta }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ consultum.fecha ? consultum.fecha|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_consulta_index') }}">back to list</a>

    <a href="{{ path('app_consulta_edit', {'id': consultum.id}) }}">edit</a>

    {{ include('consulta/_delete_form.html.twig') }}
{% endblock %}