src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

  /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_registro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Apellido;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cedula;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Profesion;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $image;

    private $rawPhoto;

    /**
     * @ORM\OneToMany(targetEntity=Consulta::class, mappedBy="user", orphanRemoval=true)
     */
    private $consultas;

public function displayPhoto()
{
    if(null === $this->rawPhoto && $this->getImage() != null) {
        $this->rawPhoto = "data:image/png;base64," . base64_encode(stream_get_contents($this->getImage()));
    }

    return $this->rawPhoto;
}

    public function __construct()
    {
    
        $this->is_active = true;
        $this->fecha_registro= new \DateTime();
        $this->consultas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getFechaRegistro(): ?\DateTimeInterface
    {
        return $this->fecha_registro;
    }

    public function setFechaRegistro(\DateTimeInterface $fecha_registro): self
    {
        $this->fecha_registro = $fecha_registro;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(?string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(?string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getCedula(): ?string
    {
        return $this->cedula;
    }

    public function setCedula(?string $cedula): self
    {
        $this->cedula = $cedula;

        return $this;
    }

    public function getProfesion(): ?string
    {
        return $this->Profesion;
    }

    public function setProfesion(?string $Profesion): self
    {
        $this->Profesion = $Profesion;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Consulta>
     */
    public function getConsultas(): Collection
    {
        return $this->consultas;
    }

    public function addConsulta(Consulta $consulta): self
    {
        if (!$this->consultas->contains($consulta)) {
            $this->consultas[] = $consulta;
            $consulta->setUser($this);
        }

        return $this;
    }

    public function removeConsulta(Consulta $consulta): self
    {
        if ($this->consultas->removeElement($consulta)) {
            // set the owning side to null (unless already changed)
            if ($consulta->getUser() === $this) {
                $consulta->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('cedula')
            ->add('Nombre')
            ->add('Apellido')
            ->add('Profesion')
            ->add('roles')
            ->add('is_active')
             
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserEditType;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }


    /**
     * @Route("/{id}", name="app_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

       /**
     * @Route("/{id}/edit_user", name="user_profile", methods={"GET", "POST"})
     */
    public function edit_user(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        
        if ($form->isSubmitted() && $form->isValid()) {
            $file=  $form->get('image')->getData();
            if ($file) {
         
                $strm = fopen($file->getRealPath(),'rb');
         
                // Move the file to the directory where brochures are stored
                try {

                  $user->setImage(stream_get_contents($strm));

                 
  
                
                } catch (Exception $e) {
                    throw  new \Exception('Error al subir archivos');
                    // ... handle exception if something happens during file upload
                }

                
    
            }

            $userRepository->add($user, true);

            return $this->redirect($request->getUri());
        }

        return $this->renderForm('user/edit_user.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
    
  

    /**
     * @Route("/{id}", name="app_user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Borrar</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/edit_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Editar Perfil</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Actualizar'}) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>Usuarios</h1>
<div class="card">
  <div class="card-body">
   <a href="{{ path('app_register') }}"><i class="fa fa-plus-square" aria-hidden="true"></i></a>
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Email</th>
                <th>Imagen</th>
                <th>Cedula</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Roles</th>
                <th>Verificado</th>
                <th>Activo</th>
                <th>Fecha_registro</th> 
                <th>Profesion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
     
                <td>{{ user.email }}</td>
                <td>
                  {% if  user.displayPhoto is defined and user.displayPhoto   is null  %}
                   
                  {% elseif user.displayPhoto is defined and user.displayPhoto is not null  %}
                  <img  class="rounded" width="40%" height="60%" src="{{user.displayPhoto}}" >
                  {% endif %}
                </td>
                <td>{{ user.cedula }}</td>
                <td>{{ user.Nombre }}</td>
                <td>{{ user.Apellido }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.isVerified ? 'No' : 'Si' }}</td>
                <td>{{ user.isActive ? 'No' : 'Si' }}</td>
                <td>{{ user.fechaRegistro ? user.fechaRegistro|date('Y-m-d') : '' }}</td>
                <td>{{ user.Profesion }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}"><i class="fa fa-pencil-square" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>

   
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script>
$(document).ready(function () {
    $('#example').DataTable({
          responsive: true,
          language: {
            url:"{{ asset('datatables/js/Spanish.json') }}"
        }
    });
});
</script>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/new_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello InicioController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
  <h1> Se guardo el usuario admin </h1>
  username: administrador
  contraseña: admin@admin.com
  !Cambiar los datos del usario Adminstrador una vez creado¡
  </br>
  <a href="{{ path('app_login') }}">Iniciar Session</a>
</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
          <tr>
                <th>Image</th>
                <td><img  class="rounded" width="20%" height="40%" src="{{user.displayPhoto}}" ></td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Verificado</th>
                <td>{{ user.isVerified ? 'No' : 'Si' }}</td>
            </tr>
            <tr>
                <th>Activo</th>
                <td>{{ user.isActive ? 'No' : 'Si' }}</td>
            </tr>
            <tr>
                <th>Fecha_registro</th>
                <td>{{ user.fechaRegistro ? user.fechaRegistro|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ user.Nombre }}</td>
            </tr>
            <tr>
                <th>Apellido</th>
                <td>{{ user.Apellido }}</td>
            </tr>
            <tr>
                <th>Cedula</th>
                <td>{{ user.cedula }}</td>
            </tr>
            <tr>
                <th>Profesion</th>
                <td>{{ user.Profesion }}</td>
            </tr>
          
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}